export const categories = [
  {
    title: 'Thiết bị điện tử',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Phụ kiện điện tử',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'TV &amp; Thiết bị gia dụng',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Sức khỏe &amp; Làm đẹp',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Mẹ & Bé, Đồ chơi',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Siêu thị tạp hóa',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Hàng gia dụng & Đời sống',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Thời trang nam',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Thời trang nữ',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Phụ kiện thời trang',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Thể thao & Du lịch',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
  {
    title: 'Ôtô, Xe máy & Thiết bị định vị',
    nested: [
      { title: 'Thiết bị điện tử' },
      { title: 'Phụ kiện điện tử' },
      { title: 'TV &amp; Thiết bị gia dụng' },
      { title: 'Sức khỏe &amp; Làm đẹp' },
      { title: 'Mẹ &amp; Bé, Đồ chơi' },
      { title: 'Siêu thị tạp hóa' },

      { title: 'Hàng gia dụng &amp; Đời sống' },
      { title: 'Thời trang nam' },
      { title: 'Thời trang nữ' },
      { title: 'Phụ kiện thời trang' },
      { title: 'Thể thao &amp; Du lịch' },
      { title: 'Ôtô, Xe máy &amp; Thiết bị định vị' },
    ],
  },
]
